/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package inventariofarmacia;

import Modelo.DatosCompartidos;
import Modelo.Producto;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author lapto
 */
public class JInternalFrameStock extends javax.swing.JInternalFrame {

    // Guardará el producto que encontremos para poder usarlo
    // tanto en el botón "Buscar" como en el botón "Guardar Cambios".
    private Producto productoEncontrado;

    /**
     * Creates new form JInternalFrameStock
     */
    public JInternalFrameStock() {
        initComponents();
    }
    

    
    private void limpiarCampos() {
        jTextFieldID.setText("");
        jTextFieldNombreP.setText("");
        jTextFieldCodigo.setText("");
        jTextFieldDescripcion.setText("");
        jTextFieldUnidadM.setText("");
        jTextFieldPrecioC.setText("");
        jTextFieldPorsentajeG1.setText("");
        jTextFieldStockM.setText("");
        jTextFieldLote.setText("");
        FechaV.setText("");
        jTextFieldCategoria.setText("");
        jTextFieldPresentacion.setText("");
        jTextFieldPrecioV.setText("");
        jTextFieldStockI.setText("");

        // También limpiamos la variable clave y el buscador
        this.productoEncontrado = null;
        jTextFieldBuscar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPorsentajeG = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPorsentajeG1 = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldNombreP = new javax.swing.JTextField();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jTextFieldUnidadM = new javax.swing.JTextField();
        jTextFieldPrecioC = new javax.swing.JTextField();
        jTextFieldStockM = new javax.swing.JTextField();
        FechaV = new javax.swing.JFormattedTextField();
        jTextFieldLote = new javax.swing.JTextField();
        jTextFieldCategoria = new javax.swing.JTextField();
        jTextFieldPresentacion = new javax.swing.JTextField();
        jTextFieldPrecioV = new javax.swing.JTextField();
        jTextFieldStockI = new javax.swing.JTextField();
        jButtonActualizar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabelCerrar = new javax.swing.JLabel();

        jTextFieldPorsentajeG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPorsentajeGKeyTyped(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actualizar Stock", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Descripción:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Codigo:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Unidad de medida:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Precio de compra:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Porsentaje de ganancia:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Stock Minimo:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Lote:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Fecha de vencimiento:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Categoria:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Presentación:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Precio de venta:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Stock Inicial:");

        jTextFieldPorsentajeG1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPorsentajeG1KeyTyped(evt);
            }
        });

        jTextFieldID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDKeyTyped(evt);
            }
        });

        jTextFieldNombreP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombrePKeyTyped(evt);
            }
        });

        jTextFieldCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyTyped(evt);
            }
        });

        jTextFieldDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDescripcionKeyTyped(evt);
            }
        });

        jTextFieldUnidadM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldUnidadMKeyTyped(evt);
            }
        });

        jTextFieldPrecioC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioCKeyTyped(evt);
            }
        });

        jTextFieldStockM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStockMKeyTyped(evt);
            }
        });

        try {
            FechaV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTextFieldLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLoteKeyTyped(evt);
            }
        });

        jTextFieldCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCategoriaKeyTyped(evt);
            }
        });

        jTextFieldPresentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPresentacionKeyTyped(evt);
            }
        });

        jTextFieldPrecioV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioVKeyTyped(evt);
            }
        });

        jTextFieldStockI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStockIKeyTyped(evt);
            }
        });

        jButtonActualizar.setBackground(new java.awt.Color(0, 0, 153));
        jButtonActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonActualizar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPrecioC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldUnidadM, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPorsentajeG1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 72, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldBuscar)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonCancelar)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecioV, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLote, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStockM, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaV, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStockI, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonBuscar))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldStockM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldUnidadM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldPrecioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecioV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldPorsentajeG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStockI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonActualizar)
                    .addComponent(jButtonCancelar))
                .addGap(30, 30, 30))
        );

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariofarmacia/close-fill (1) (1).png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCerrar)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelCerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPorsentajeGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPorsentajeGKeyTyped
        char c = evt.getKeyChar();
        JTextField field = (JTextField) evt.getSource();
        String texto = field.getText();

        if (Character.isDigit(c)) {
            if (texto.contains("%")) {
                // No permitir números después del %
                evt.consume();
            }
        } else if (c == '%') {
            if (texto.contains("%") || texto.isEmpty()) {
                // No permitir más de un % o si se escribe como primer carácter
                evt.consume();
            }
        } else {
            // Bloquear cualquier otro carácter
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPorsentajeGKeyTyped

    private void jTextFieldPorsentajeG1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPorsentajeG1KeyTyped
        char c = evt.getKeyChar();
        JTextField field = (JTextField) evt.getSource();
        String texto = field.getText();

        if (Character.isDigit(c)) {
            if (texto.contains("%")) {
                // No permitir números después del %
                evt.consume();
            }
        } else if (c == '%') {
            if (texto.contains("%") || texto.isEmpty()) {
                // No permitir más de un % o si se escribe como primer carácter
                evt.consume();
            }
        } else {
            // Bloquear cualquier otro carácter
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPorsentajeG1KeyTyped

    private void jTextFieldIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDKeyTyped
        char car = evt.getKeyChar();
        // Solo permite números del 0 al 9
        if (car < '0' || car > '9') {
            evt.consume(); // Ignora el carácter si no es un número
        }

    }//GEN-LAST:event_jTextFieldIDKeyTyped

    private void jTextFieldNombrePKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombrePKeyTyped
        char c = evt.getKeyChar();

        // Permitimos letras (mayúsculas y minúsculas), espacios, ñ, Ñ y vocales acentuadas
        if (!Character.isLetter(c)
                && c != ' '
                && c != 'ñ' && c != 'Ñ'
                && c != 'á' && c != 'é' && c != 'í' && c != 'ó' && c != 'ú'
                && c != 'Á' && c != 'É' && c != 'Í' && c != 'Ó' && c != 'Ú') {
            evt.consume(); // Ignora cualquier otro carácter
        }

    }//GEN-LAST:event_jTextFieldNombrePKeyTyped

    private void jTextFieldCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetterOrDigit(c)) {
            evt.consume(); // No permite caracteres que no sean letras o números
        }

    }//GEN-LAST:event_jTextFieldCodigoKeyTyped

    private void jTextFieldDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionKeyTyped
        char car = evt.getKeyChar();

        // Permite letras y espacios únicamente
        if (!Character.isLetter(car) && car != KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDescripcionKeyTyped

    private void jTextFieldUnidadMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUnidadMKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetterOrDigit(c)) {
            evt.consume(); // No permite caracteres que no sean letras o números
        }
    }//GEN-LAST:event_jTextFieldUnidadMKeyTyped

    private void jTextFieldPrecioCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioCKeyTyped
        char car = evt.getKeyChar();
        // Solo permite números del 0 al 9
        if (car < '0' || car > '9') {
            evt.consume(); // Ignora el carácter si no es un número
        }
    }//GEN-LAST:event_jTextFieldPrecioCKeyTyped

    private void jTextFieldStockMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockMKeyTyped
        char car = evt.getKeyChar();
        // Solo permite números del 0 al 9
        if (car < '0' || car > '9') {
            evt.consume(); // Ignora el carácter si no es un número
        }
    }//GEN-LAST:event_jTextFieldStockMKeyTyped

    private void jTextFieldLoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLoteKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetterOrDigit(c)) {
            evt.consume(); // No permite caracteres que no sean letras o números
        }
    }//GEN-LAST:event_jTextFieldLoteKeyTyped

    private void jTextFieldCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCategoriaKeyTyped
        char car = evt.getKeyChar();

        // Permite letras y espacios únicamente
        if (!Character.isLetter(car) && car != KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCategoriaKeyTyped

    private void jTextFieldPresentacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPresentacionKeyTyped
         char c = evt.getKeyChar();
        // permite letras (incluye ñ y acentos), numeros y espacio
        if (!Character.isLetterOrDigit(c)
                && c != ' '
                && c != 'ñ' && c != 'Ñ'
                && c != 'á' && c != 'é' && c != 'í' && c != 'ó' && c != 'ú'
                && c != 'Á' && c != 'É' && c != 'Í' && c != 'Ó' && c != 'Ú') {
            evt.consume(); // Ignora cualquier otro carácter
        }

    }//GEN-LAST:event_jTextFieldPresentacionKeyTyped

    private void jTextFieldPrecioVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioVKeyTyped
        char car = evt.getKeyChar();
        // Solo permite números del 0 al 9
        if (car < '0' || car > '9') {
            evt.consume(); // Ignora el carácter si no es un número
        }
    }//GEN-LAST:event_jTextFieldPrecioVKeyTyped

    private void jTextFieldStockIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockIKeyTyped
        char car = evt.getKeyChar();
        // Solo permite números del 0 al 9
        if (car < '0' || car > '9') {
            evt.consume(); // Ignora el carácter si no es un número
        }
    }//GEN-LAST:event_jTextFieldStockIKeyTyped

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String nombreBuscado = jTextFieldBuscar.getText().trim();

        if (nombreBuscado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre para buscar.");
            return;
        }

        // Reiniciamos la variable clave
        this.productoEncontrado = null;

        // Buscamos en la lista GLOBAL
        for (Producto p : DatosCompartidos.listaProducto) {
            if (p.getNombre().equalsIgnoreCase(nombreBuscado)) {
                this.productoEncontrado = p; // ¡Lo encontramos! Lo guardamos en la variable clave
                break; // Salimos del bucle
            }
        }

        //  llenamos las 14 cajas de texto 
        if (this.productoEncontrado != null) {
            // Si lo encontramos, llenamos todos los campos

            // Usamos los "getters" del objeto 'productoEncontrado'
            // Los números (int, double) deben convertirse a String
            jTextFieldID.setText(String.valueOf(productoEncontrado.getID()));
            jTextFieldNombreP.setText(productoEncontrado.getNombre());
            jTextFieldCodigo.setText(productoEncontrado.getCodigo());
            jTextFieldDescripcion.setText(productoEncontrado.getDescripcion());
            jTextFieldUnidadM.setText(productoEncontrado.getUnidadM());
            jTextFieldPrecioC.setText(String.valueOf(productoEncontrado.getPrecioC()));
            jTextFieldPorsentajeG1.setText(String.valueOf(productoEncontrado.getPorsentajeG()));
            jTextFieldStockM.setText(String.valueOf(productoEncontrado.getStockM()));
            jTextFieldLote.setText(productoEncontrado.getLote());
            FechaV.setText(productoEncontrado.getFechaV());
            jTextFieldCategoria.setText(productoEncontrado.getCategoria());
            jTextFieldPresentacion.setText(productoEncontrado.getPresentacion());
            jTextFieldPrecioV.setText(String.valueOf(productoEncontrado.getPrecioV()));

            // El campo de stock/existencia
            jTextFieldStockI.setText(String.valueOf(productoEncontrado.getStockI()));

        } else {
            // Si no lo encontramos, mostramos un mensaje y limpiamos las cajas
            JOptionPane.showMessageDialog(this, "Producto no encontrado.");
            limpiarCampos(); // llama al metodo limpiarCampos
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed

        // 1. Verificamos que SÍ tengamos un producto cargado
        if (this.productoEncontrado == null) {
            JOptionPane.showMessageDialog(this, "Primero debe buscar un producto antes de guardar.");
            return;
        }

        //validar que todos los campos de texto no esten vacios
        if ((jTextFieldID.getText().contentEquals(""))
                || (jTextFieldNombreP.getText().contentEquals(""))
                || (jTextFieldCodigo.getText().contentEquals(""))
                || (jTextFieldDescripcion.getText().contentEquals(""))
                || (jTextFieldUnidadM.getText().contentEquals(""))
                || (jTextFieldPrecioC.getText().contentEquals(""))
                || (jTextFieldPorsentajeG1.getText().contentEquals(""))
                || (jTextFieldStockM.getText().contentEquals(""))
                || (jTextFieldLote.getText().contentEquals(""))
                || (FechaV.getText().contentEquals(""))
                || (jTextFieldCategoria.getText().contentEquals(""))
                || (jTextFieldPresentacion.getText().contentEquals(""))
                || (jTextFieldPrecioV.getText().contentEquals(""))
                || (jTextFieldStockI.getText().contentEquals(""))) {
            //Mensaje para informar si algun campo esta vacio // Agrego import
            JOptionPane.showMessageDialog(null,
                    "Algunos campos estan vacios",
                    "!Revise todos los campos!",
                    JOptionPane.WARNING_MESSAGE);
            return;

        }
        try {
            // Recuperamos y convertimos todos los nuevos valores
            String nombreProducto = jTextFieldNombreP.getText().trim();
            String codigo = jTextFieldCodigo.getText().trim();
            String descripcion = jTextFieldDescripcion.getText().trim();
            String unidadMedida = jTextFieldUnidadM.getText().trim();
            String lote = jTextFieldLote.getText().trim();
            String fechaVencimiento = FechaV.getText().trim();
            String categoria = jTextFieldCategoria.getText().trim();
            String presentacion = jTextFieldPresentacion.getText().trim();
            // Convertimos los datos numericos
            double precioCompra = Double.parseDouble(jTextFieldPrecioC.getText().trim());
            double porsentage = Double.parseDouble(jTextFieldPorsentajeG1.getText().trim());
            int stockM = Integer.parseInt(jTextFieldStockM.getText().trim());
            double precioV = Double.parseDouble(jTextFieldPrecioV.getText().trim());
            int stockI = Integer.parseInt(jTextFieldStockI.getText().trim());
            int id = Integer.parseInt(jTextFieldID.getText().trim());

            this.productoEncontrado.setNombre(nombreProducto);
            this.productoEncontrado.setCodigo(codigo);
            this.productoEncontrado.setDescripcion(descripcion);
            this.productoEncontrado.setUnidadM(unidadMedida);
            this.productoEncontrado.setLote(lote);
            this.productoEncontrado.setFechaV(fechaVencimiento);
            this.productoEncontrado.setCategoria(categoria);
            this.productoEncontrado.setPresentacion(presentacion);
            this.productoEncontrado.setPrecioC(precioCompra);
            this.productoEncontrado.setPorsentajeG(porsentage);
            this.productoEncontrado.SetStockM(stockM);
            this.productoEncontrado.setPrecioV(precioV);
            this.productoEncontrado.setStockI(stockI);
            this.productoEncontrado.setID(id);

            // Se le avisa al formulario de productos para actualizar la tabla
            if (JInternalFrameProducto.instanciaAbierta != null) {
                JInternalFrameProducto.instanciaAbierta.cargarTabla();
            }
            // Mostramos un mensaje confirmando la actualizacion
            JOptionPane.showMessageDialog(this, "!Producto " + nombreProducto +  "Actualizado Correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(this,
                    "Error de formato en campos numericos. verifique que los campos númericos (precio, stock) contengan solo números validos.",
                    "Error de conversión",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showConfirmDialog(this, "Ocurrio un error inesperado al actualizar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // llama al metodo limpiarCampos
        limpiarCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        try {
            this.setClosed(true);

        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FechaV;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldLote;
    private javax.swing.JTextField jTextFieldNombreP;
    private javax.swing.JTextField jTextFieldPorsentajeG;
    private javax.swing.JTextField jTextFieldPorsentajeG1;
    private javax.swing.JTextField jTextFieldPrecioC;
    private javax.swing.JTextField jTextFieldPrecioV;
    private javax.swing.JTextField jTextFieldPresentacion;
    private javax.swing.JTextField jTextFieldStockI;
    private javax.swing.JTextField jTextFieldStockM;
    private javax.swing.JTextField jTextFieldUnidadM;
    // End of variables declaration//GEN-END:variables
}
