/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package inventariofarmacia;


import Modelo.Usuario;
import java.util.ArrayList; 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDialog;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;

/**
 *
 * @author lapto
 */
public class JInternalFrameUsuario extends javax.swing.JInternalFrame {
    
     //Lista donde se gurdan los Usuario*
    ArrayList<Usuario> listaUsuario=new ArrayList<>();
    int indice= -1 ;// Variable utilizada para Editar / Actualizar

    /**
     * Creates new form JInternalFrameUsuario
     */
    public JInternalFrameUsuario() {
        initComponents();
    }
    
    private void limpiarCampos(){//Métodos para limpiar cjas de texto
       //Se asinga un valor vacío a todas las cajas de texto 
       //Se utiliza el nombre de variable asignada
     jTextFieldNombreC.setText("");
     jTextFieldCorreo.setText("");
     jBoxRol.setSelectedIndex(0);
     jFieldContraseña.setText("");
       
   }
    private void llenarTabla(){
      DefaultTableModel modelo = new DefaultTableModel();
      //Arreglo con nombre de la columnas de la tabla 
      String [] columna  = {"Nombre Completo","Correo","Rol"};
      //Establece los nombre definidos de las columnas 
      modelo.setColumnIdentifiers(columna);
      //Ciclo para recorrer la lista a un arreglo
      for(Usuario u: listaUsuario){
          //Agrega cada elemento de la lista a un arreglo 
          //Utiliza un objeto pro del tipo clase usuario para obtener 
          // dato del cada atributo, a traves de método get 
          String [] renglon = {u.getNombreCompleto(), u.getCorreo(),
              u.getRol(),u.getContraseña()};
          modelo.addRow(renglon);
      }
      //Agrega todos loe elementos de arreglo renglon a la tabla usuario 
      jTableUsuario.setModel(modelo);
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombreC = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jBoxRol = new javax.swing.JComboBox<>();
        jFieldContraseña = new javax.swing.JPasswordField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonlimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jLabelCerrar = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar usuarios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Nombre Completo:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Rol:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Contraseña:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Correo:");

        jBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor" }));

        jButtonGuardar.setBackground(new java.awt.Color(51, 153, 0));
        jButtonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(0, 51, 204));
        jButtonEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonActualizar.setBackground(new java.awt.Color(0, 102, 102));
        jButtonActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonEliminar.setBackground(new java.awt.Color(153, 0, 0));
        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonlimpiar.setBackground(new java.awt.Color(153, 153, 153));
        jButtonlimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonlimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonlimpiar.setText("Limpiar");
        jButtonlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlimpiarActionPerformed(evt);
            }
        });

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jTableUsuario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonGuardar)
                                .addGap(27, 27, 27)
                                .addComponent(jButtonEditar)
                                .addGap(27, 27, 27)
                                .addComponent(jButtonActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEliminar)
                                .addGap(34, 34, 34)
                                .addComponent(jButtonlimpiar)))
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonlimpiar)
                    .addComponent(jButtonActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariofarmacia/close-fill (1) (1).png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCerrar)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelCerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        //Obtener los valores de los campos
        String nombre = jTextFieldNombreC.getText().trim();
        String correo = jTextFieldCorreo.getText().trim();
        String rol = jBoxRol.getSelectedItem().toString();
        String contraseña = new String(jFieldContraseña.getPassword());

        //Validar que no estén vacíos
        if (nombre.isEmpty() || correo.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(null,
                "Por favor, complete todos los campos",
                "Campos Vacíos",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Agrega el nuevo Usuario en la lista
        Usuario nuevoUsuario = new Usuario (nombre, correo, rol, contraseña);
        listaUsuario.add(nuevoUsuario);

        // Actualizar la tabla
        llenarTabla();

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(null, "Usuario guardado correctamente");
        limpiarCampos();

    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        // Obtener la fila seleccionada en la tabla
        int filaSeleccionada = jTableUsuario.getSelectedRow();

        // Validar si se seleccionó una fila
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null,
                "Seleccione una fila de la tabla para editar",
                "Advertencia",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener el usuario seleccionado de la lista
        Usuario usuario = listaUsuario.get(filaSeleccionada);

        //  Pasar los datos del usuario a los campos de texto
        jTextFieldNombreC.setText(usuario.getNombreCompleto());
        jTextFieldCorreo.setText(usuario.getCorreo());
        jBoxRol.setSelectedItem(usuario.getRol());
        jFieldContraseña.setText(usuario.getContraseña());

    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        int filaSeleccionada = jTableUsuario.getSelectedRow();

        // Validar si el usuario seleccionó una fila
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null,"Seleccione una fila de la tabla para actualizar",
                "Advertencia",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener los nuevos valores desde los campos
        String nombre = jTextFieldNombreC.getText().trim();
        String correo = jTextFieldCorreo.getText().trim();
        String rol = jBoxRol.getSelectedItem().toString();
        String contraseña = new String(jFieldContraseña.getPassword());

        if (nombre.isEmpty() || correo.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Por favor, complete todos los campos",
                "Campos Vacíos",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Confirmar la actualización
        int confirmacion = JOptionPane.showConfirmDialog( null, "¿Desea actualizar este usuario?",
            "Confirmar Actualización",
            JOptionPane.YES_NO_OPTION );

        if (confirmacion == JOptionPane.YES_OPTION) {
            // Actualizar el usuario en la lista
            Usuario usuario = listaUsuario.get(filaSeleccionada);
            usuario.setNombreCompleto(nombre);
            usuario.setCorreo(correo);
            usuario.setRol(rol);
            usuario.setContraseña(contraseña);

            llenarTabla();

            // Mostrar mensaje y limpiar campos
            JOptionPane.showMessageDialog(null, "Usuario actualizado correctamente");
            limpiarCampos();
        }

    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int fila = this.jTableUsuario.getSelectedRow(); // Se obtiene el #fila seleccionado

        // Se verifica que esté seleccionada una fila de la tabla
        if (fila == -1) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
            return;
        }

        // Se construye el mensaje de confirmación incluyendo el número de fila.
        // Se usa la variable 'fila' directamente para que comience desde 0.
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la fila número " + fila +
            "?","Eliminando...", JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        // Si la respuesta es sí se elimina
        if (resp == JOptionPane.YES_OPTION) {
            // Método remove para quitar de la lista la fila seleccionada
            // La numeración de la fila de la tabla es igual a las posiciones de la lista
            listaUsuario.remove(fila);
            // Se llama al método llenarTabla para mostrar los datos actuales de la lista
            llenarTabla();
            JOptionPane.showMessageDialog(null, "Usuario eliminado correctamente");
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlimpiarActionPerformed
        //Llamada al método limpiar campos
        limpiarCampos();
    }//GEN-LAST:event_jButtonlimpiarActionPerformed

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        try {
            this.setClosed(true);

        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jBoxRol;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonlimpiar;
    private javax.swing.JPasswordField jFieldContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombreC;
    // End of variables declaration//GEN-END:variables
}
