/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package inventariofarmacia;

import Modelo.DatosCompartidos;
import Modelo.Producto;
import javax.swing.JOptionPane;
import Modelo.DetalleVenta;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lapto
 */
public class JInternalFrameVentas extends javax.swing.JInternalFrame {
     ArrayList<DetalleVenta> listaVenta = new ArrayList<>();
    DefaultTableModel modeloTabla;
    double total = 0;

    /**
     * Creates new form JInternalFrameVentas
     */
    public JInternalFrameVentas() {
        initComponents();
        
         inicializarTabla();
    }
    
    // Configurar tabla 
    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel(
                new Object[]{"Producto", "Cantidad", "Precio", "Descuento", "Subtotal"}, 0
        );
        jTableProductos.setModel(modeloTabla);

    }

    // CALCULAR CAMBIO AUTOMÁTICAMENTE 
    private void txtipodepagoActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            double pago = Double.parseDouble(txtipodepago.getText());
            double cambio = pago - total;
            jLabel23.setText("C$ " + String.format("%.2f", cambio));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese una cantidad de pago válida.");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nombrebusca = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cerostock = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ceroprecio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txtipodepago = new javax.swing.JTextField();
        Agregar2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        ventafinalizada = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setBorder(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar ventas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText(" Nombre ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        nombrebusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrebuscaActionPerformed(evt);
            }
        });
        jPanel1.add(nombrebusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 340, -1));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        jLabel3.setText("Stock disponible");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        cerostock.setText("0");
        jPanel1.add(cerostock, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 20, -1));

        jLabel5.setText("Precio");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        ceroprecio.setText("C$ 0");
        jPanel1.add(ceroprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel2.setText("Cantidad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });
        jPanel1.add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, -1));

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "producto", "cantidad", "precio", "descuento", "subtotal"
            }
        ));
        jScrollPane3.setViewportView(jTableProductos);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 110));

        jLabel20.setText("Cantidad de pago");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));
        jPanel1.add(txtipodepago, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 100, -1));

        Agregar2.setText("Agregar");
        Agregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar2ActionPerformed(evt);
            }
        });
        jPanel1.add(Agregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        jLabel21.setText("Cambio");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jLabel23.setText("C$ 0");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        jLabel19.setText("Total");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        lblTotal.setText("C$ 0");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        ventafinalizada.setText("Finalizar Venta");
        ventafinalizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventafinalizadaActionPerformed(evt);
            }
        });
        jPanel1.add(ventafinalizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, -1));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombrebuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrebuscaActionPerformed

    }//GEN-LAST:event_nombrebuscaActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String nombre = nombrebusca.getText().trim();

        Producto encontrado = DatosCompartidos.buscarProductoPorNombre(nombre);

        if (encontrado != null) {
            cerostock.setText(String.valueOf(encontrado.getStockI()));
            ceroprecio.setText(String.valueOf(encontrado.getPrecioV()));
        } else {
            JOptionPane.showMessageDialog(this, "Producto no encontrado");
            cerostock.setText("");
            ceroprecio.setText("");
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed

    }//GEN-LAST:event_txtcantidadActionPerformed

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped

    }//GEN-LAST:event_txtcantidadKeyTyped

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        String nombreBuscado = nombrebusca.getText().trim();
        if (nombreBuscado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre de producto.");
            return;
        }

        Producto encontrado = null;
        for (Producto p : DatosCompartidos.listaProducto) {
            if (p.getNombre().equalsIgnoreCase(nombreBuscado)) {
                encontrado = p;
                break;
            }
        }

        if (encontrado == null) {
            JOptionPane.showMessageDialog(this, "Producto no encontrado.");
            return;
        }

        int cantidad;
        try {
            cantidad = Integer.parseInt(txtcantidad.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese una cantidad válida.");
            return;
        }

        //Validar que la cantidad sea positiva
        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(null, "La cantidad debe ser mayor a cero.");
            return;
        }

        //  Validacion de stock (se detiene la venta sino hay exixtencia)
        if (cantidad > encontrado.getStockI()) {
            JOptionPane.showMessageDialog(null, "Stock insuficiente. Solo quedan " + encontrado.getStockI() + " unidades.");
            return;
        }

        // Se resta la cantidad del stock
        // Esto modifica el objeto 'encontrado' que está en 'DatosCompartidos.listaProducto'
        int nuevoStock = encontrado.getStockI() - cantidad;
        encontrado.setStockI(nuevoStock);

        // Se actualiza la tabla automaticamente
        // Verificamos si el formulario de productos está abierto
        if (JInternalFrameProducto.instanciaAbierta != null) {
            // Si está abierto, llamamos a su método público para recargar la tabla
            JInternalFrameProducto.instanciaAbierta.cargarTabla();
        }

        // CÓDIGO DE AVISO DE STOCK BAJO
        // Comparamos el *nuevo stock* que acabamos de calcular con el
        // *stock mínimo* que tiene guardado el producto.
        // Esto NO detiene la venta, es solo un aviso.
        if (nuevoStock <= encontrado.getStockM()) {
            JOptionPane.showMessageDialog(null, // 'this' o 'null'
                "¡Aviso! Stock bajo para: " + encontrado.getNombre() + "\n" +
                "Quedan solo " + nuevoStock + " unidades (Mínimo: " + encontrado.getStockM() + ").",
                "Aviso de Stock Bajo",
                JOptionPane.WARNING_MESSAGE); // Icono de advertencia
        }

        double precio = encontrado.getPrecioV();
        double descuento = 0;
        double subtotal = (precio * cantidad) - descuento;

        // Se actualiza el total general
        total += subtotal;
        lblTotal.setText("C$ " + String.format("%.2f", total));

        // Se crea el objeto DetalleVenta (de momento con pago y cambio = 0)
        DetalleVenta detalle = new DetalleVenta(
            encontrado.getNombre(),
            cantidad,
            precio,
            subtotal,
            0, // pago aún no ingresado
            0, // cambio aún no calculado
            total // total acumulado hasta ahora
        );

        listaVenta.add(detalle);

        // Se muestra en la tabla
        modeloTabla.addRow(new Object[]{
            encontrado.getNombre(), cantidad, precio, descuento, subtotal
        });

        // Limpia campos
        txtcantidad.setText("");
        nombrebusca.setText("");
        cerostock.setText("");
        ceroprecio.setText("");
    }//GEN-LAST:event_agregarActionPerformed

    private void Agregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar2ActionPerformed
        try {
            if (listaVenta.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay productos en la venta.");
                return;
            }

            double pago = Double.parseDouble(txtipodepago.getText());
            double cambio = pago - total;

            lblTotal.setText("C$ " + String.format("%.2f", total));
            jLabel23.setText("C$ " + String.format("%.2f", cambio));

            if (pago < total) {
                JOptionPane.showMessageDialog(this,
                    "El pago es menor al total. Faltan C$ " + String.format("%.2f", total - pago));
            } else {
                JOptionPane.showMessageDialog(this,
                    "Pago registrado correctamente.\nCambio: C$ " + String.format("%.2f", cambio));
            }

            // 🔹 Actualizamos todos los detalles con pago/cambio/total
            for (DetalleVenta detalle : listaVenta) {
                detalle.setPago(pago);
                detalle.setCambio(cambio);
                detalle.setTotal(total);
            }

            // Limpiar campo de pago
            txtipodepago.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese una cantidad de pago válida.");
        }
    }//GEN-LAST:event_Agregar2ActionPerformed

    private void ventafinalizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventafinalizadaActionPerformed
        if (listaVenta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay productos en la venta.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Deseas finalizar la venta por un total de C$ " + String.format("%.2f", total) + "?",
            "Confirmar venta",
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "✅ Venta finalizada con éxito. Total: C$ " + String.format("%.2f", total));

            // Se guarda la listaVenta  imprimir
            //  DatosCompartidos.listaVentas.addAll(listaVenta);
            // Limpiar tabla y campos
            modeloTabla.setRowCount(0);
            nombrebusca.setText("");
            txtcantidad.setText("");
            txtipodepago.setText("");
            ceroprecio.setText("C$ 0");
            cerostock.setText("0");
            lblTotal.setText("C$ 0");
            jLabel23.setText("C$ 0");
            total = 0;
            listaVenta.clear();
        } else {
            JOptionPane.showMessageDialog(this, "Venta cancelada.");
        }
    }//GEN-LAST:event_ventafinalizadaActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

        try {
            //  Obtener el pago ingresado
            String textoPago = txtipodepago.getText().trim();
            if (textoPago.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese la cantidad de pago antes de imprimir la factura.");
                return;
            }

            double pago = Double.parseDouble(textoPago);

            //  Obtener el total de la etiqueta lblTotal
            String textoTotal = lblTotal.getText().replace("C$", "").trim();
            double total = Double.parseDouble(textoTotal);

            // Calcular el cambio
            double cambio = pago - total;

            // Formatear los valores
            String pagoFormateado = String.format("%.2f", pago);
            String totalFormateado = String.format("%.2f", total);
            String cambioFormateado = String.format("%.2f", cambio);

            // Crear el texto de la factura
            StringBuilder factura = new StringBuilder("=== FACTURA ===\n\n");

            // Agregar productos desde la tabla
            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                factura.append(modeloTabla.getValueAt(i, 0)).append(" - ")
                .append("Cant: ").append(modeloTabla.getValueAt(i, 1)).append(", ")
                .append("Precio: C$").append(modeloTabla.getValueAt(i, 2)).append(", ")
                .append("Subtotal: C$").append(modeloTabla.getValueAt(i, 4)).append("\n");
            }

            // Agregar totales, pago y cambio
            factura.append("\nTotal: C$ ").append(totalFormateado)
            .append("\nPago: C$ ").append(pagoFormateado)
            .append("\nCambio: C$ ").append(cambioFormateado);

            // Mostrar la factura
            JOptionPane.showMessageDialog(this, factura.toString(), "Factura", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El valor de pago no es válido. Ingrese un número.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // Limpiar el campo de texto
        txtipodepago.setText("");

        // Reiniciar etiquetas
        jLabel23.setText("C$ 0");
        lblTotal.setText("C$ 0");

        // resetear el total
        total = 0;

        // Mostrar mensaje
        JOptionPane.showMessageDialog(this, "Operación cancelada.");
    }//GEN-LAST:event_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar2;
    private javax.swing.JButton agregar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel ceroprecio;
    private javax.swing.JLabel cerostock;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField nombrebusca;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtipodepago;
    private javax.swing.JButton ventafinalizada;
    // End of variables declaration//GEN-END:variables
}
