/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package inventariofarmacia;

/**
 *
 * @author lapto
 */
public class MDIPrincipals extends javax.swing.JFrame {

    /**
     * Creates new form MDIPrincipals
     */
    public MDIPrincipals() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        productoMenu = new javax.swing.JMenu();
        gestionProductoMenultem = new javax.swing.JMenuItem();
        RegistroVentaMenuItem = new javax.swing.JMenuItem();
        actualizarStockMenuItem = new javax.swing.JMenuItem();
        GestionUsuariosMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productoMenu.setMnemonic('f');
        productoMenu.setText("Inventario");

        gestionProductoMenultem.setMnemonic('o');
        gestionProductoMenultem.setText("Gestion de Productos");
        gestionProductoMenultem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionProductoMenultemActionPerformed(evt);
            }
        });
        productoMenu.add(gestionProductoMenultem);

        RegistroVentaMenuItem.setMnemonic('s');
        RegistroVentaMenuItem.setText("Registrar ventas");
        RegistroVentaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroVentaMenuItemActionPerformed(evt);
            }
        });
        productoMenu.add(RegistroVentaMenuItem);

        actualizarStockMenuItem.setMnemonic('a');
        actualizarStockMenuItem.setText("Actualizar Stock");
        actualizarStockMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarStockMenuItemActionPerformed(evt);
            }
        });
        productoMenu.add(actualizarStockMenuItem);

        GestionUsuariosMenuItem.setMnemonic('x');
        GestionUsuariosMenuItem.setText("Gestion de Usuarios");
        GestionUsuariosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionUsuariosMenuItemActionPerformed(evt);
            }
        });
        productoMenu.add(GestionUsuariosMenuItem);

        menuBar.add(productoMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionUsuariosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionUsuariosMenuItemActionPerformed
        JInternalFrameUsuario jframeUsuario = new JInternalFrameUsuario();
        desktopPane.add(jframeUsuario);
        jframeUsuario.show();
    }//GEN-LAST:event_GestionUsuariosMenuItemActionPerformed

    private void gestionProductoMenultemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionProductoMenultemActionPerformed
        JInternalFrameProducto jframeProducto = new JInternalFrameProducto();
        desktopPane.add(jframeProducto);
        jframeProducto.show();
    }//GEN-LAST:event_gestionProductoMenultemActionPerformed

    private void RegistroVentaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroVentaMenuItemActionPerformed
        JInternalFrameVentas jframeVentas = new JInternalFrameVentas();
        desktopPane.add(jframeVentas);
        jframeVentas.show();
    }//GEN-LAST:event_RegistroVentaMenuItemActionPerformed

    private void actualizarStockMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarStockMenuItemActionPerformed
        JInternalFrameStock jframeStock = new JInternalFrameStock();
        desktopPane.add(jframeStock);
        jframeStock.show();
    }//GEN-LAST:event_actualizarStockMenuItemActionPerformed
    //System.exit(0);

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIPrincipals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GestionUsuariosMenuItem;
    private javax.swing.JMenuItem RegistroVentaMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem actualizarStockMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem gestionProductoMenultem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenu productoMenu;
    // End of variables declaration//GEN-END:variables

}
